/// Flutter icons MetaIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MetaIcons
///      fonts:
///       - asset: fonts/MetaIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MetaIcons {
  MetaIcons._();

  static const _kFontFam = 'MetaIcons';
  static const String? _kFontPkg = null;

  static const IconData arrow_back = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attach = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call_video = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gallery = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData happy_face = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gif = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData microphone = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_filled_round = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData navigation = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData people = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData preferences = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData speech_bubble = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sticker = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData text = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumb_up = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wave_hand = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sticker_face = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
